### ISSUE TITLE
Regarding the API's OAuth

### ISSUE THREAD

**Issue by BShadid** [BShadid/twitterRNN#1]
I did not realize that Twitter implemented OAuth for their API. We'll need to figure out how to work around this, which might involve [registering a new twitter application](https://apps.twitter.com/app/new). For more details on this, [read this](https://dev.twitter.com/oauth/overview/introduction).

**Comment by BShadid** [comment]
I started working with the [tweepy](https://github.com/tweepy/tweepy) package, which will simplify our interaction with the API. Let's start with this for now, and we'll code our own version of this if we have time. Creating our own Twitter API library may be beyond the scope of this project.

Since we don't have root permissions on student machines, the installation process is a bit complicated, as we each have to install python packages locally:

$ pip install --user tweepy
$ export PYTHONPATH=~/.local/lib/python2.7/site-packages/tweepy

I would recommend adding this PYTHONPATH to your ~/.bashrc file. From here, you should be able to include the command "import tweepy" in a python script without any issues. 

You might be able to bypass this installation process by running "python setup.py build" after cloning the repository. (git clone https://github.com/tweepy/tweepy.git && cd tweepy). I think I managed to do this somehow, but I'm not quite sure how it works. The pip method should work, and intuitively makes more sense than the build method.

I've started a new twitter account for this project, since we need one for the OAuth process. I'll write the information for this and share it over Google Drive. I'll include a sample script called **test.py** in the repository giving an example of how to use the API.

Other than the installation issues, I think the OAuth problem has been addressed (at least until we decide to write our own API library).

**Comment by BShadid** [comment]
I'll reopen this until I get confirmation that this has been done successfully.

**Comment by jcbbeiter** [comment]
I was able to successfully use the test code (and accidentally tweet) just by importing tweepy.

**Comment by BShadid** [comment]
The tweepy package should work for all users on all student machines without having to install it into a local directory.
